# Docker Compose file for Vapor
#
# Install Docker on your system to run and test
# your Vapor app in a production-like environment.
#
# Note: This file is intended for testing and does not
# implement best practices for a production deployment.
#
# Learn more: https://docs.docker.com/compose/reference/
#
#   Build images: docker compose build
#      Start app: docker compose up app
#       Stop all: docker compose down
#

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  app:
    image: abhishek_rest_api:latest
    build:
      context: .
    environment:
      <<: *shared_environment
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USERNAME: vapor_user
      DATABASE_PASSWORD: password
      DATABASE_NAME: common_db
      CERT_PATH: /app/cert.pem
      KEY_PATH: /app/key.pem
    ports:
      - '8080:8080'
      - '443:8080'
    restart: always
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0"]
    volumes:
      - ./cert.pem:/app/cert.pem:ro
      - ./key.pem:/app/key.pem:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: common_db
      MYSQL_USER: vapor_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

